package model.AM;

import java.sql.CallableStatement;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import model.VO.AdresseVOImpl;
import model.VO.ContribuableVOImpl;

import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 28 14:50:55 CEST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContribuableAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ContribuableAMImpl() {
    }

    /**
     * Container's getter for ContribuableVO1.
     * @return ContribuableVO1
     */
    public ContribuableVOImpl getContribuableVO1() {
        return (ContribuableVOImpl) findViewObject("ContribuableVO1");
    }

    /**
     * Container's getter for AdresseVO1.
     * @return AdresseVO1
     */
    public AdresseVOImpl getAdresseVO1() {
        return (AdresseVOImpl) findViewObject("AdresseVO1");
    }

    /**
     * Container's getter for ContribuableVO2.
     * @return ContribuableVO2
     */
    public ContribuableVOImpl getContribuableVO2() {
        return (ContribuableVOImpl) findViewObject("ContribuableVO2");
    }

    /**
     * Container's getter for ComptebancaireVO1.
     * @return ComptebancaireVO1
     */
    public ViewObjectImpl getComptebancaireVO1() {
        return (ViewObjectImpl) findViewObject("ComptebancaireVO1");
    }

    /**
     * Container's getter for ContribuableVO3.
     * @return ContribuableVO3
     */
    public ContribuableVOImpl getContribuableVO3() {
        return (ContribuableVOImpl) findViewObject("ContribuableVO3");
    }

    /**
     * Container's getter for ActiviteentrepriseVO1.
     * @return ActiviteentrepriseVO1
     */
    public ViewObjectImpl getActiviteentrepriseVO1() {
        return (ViewObjectImpl) findViewObject("ActiviteentrepriseVO1");
    }

    /**
     * Container's getter for SysC0014181Link.
     * @return SysC0014181Link
     */
    public ViewLinkImpl getSysC0014181Link() {
        return (ViewLinkImpl) findViewLink("SysC0014181Link");
    }

    /**
     * Container's getter for SysC0014194Link.
     * @return SysC0014194Link
     */
    public ViewLinkImpl getSysC0014194Link() {
        return (ViewLinkImpl) findViewLink("SysC0014194Link");
    }

    /**
     * Container's getter for SysC0014177Link.
     * @return SysC0014177Link
     */
    public ViewLinkImpl getSysC0014177Link() {
        return (ViewLinkImpl) findViewLink("SysC0014177Link");
    }
    
    public boolean getAllContribuable (){
        PreparedStatement createPreparedStatement = getDBTransaction().createPreparedStatement(""+"select nomCommerciale,raisonSociale,registreCommerce from Contribuable", 0);
        Boolean result = Boolean.FALSE;
        ResultSet resultSet = null;
        try{
            resultSet = createPreparedStatement.executeQuery();
            if (resultSet.next()) {
             result = Boolean.TRUE;   
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        return result;
    }

    /**
     * Container's getter for ComptebancaireVO2.
     * @return ComptebancaireVO2
     */
    public ViewObjectImpl getComptebancaireVO2() {
        return (ViewObjectImpl) findViewObject("ComptebancaireVO2");
    }

    /**
     * Container's getter for ContriCbVl1.
     * @return ContriCbVl1
     */
    public ViewLinkImpl getContriCbVl1() {
        return (ViewLinkImpl) findViewLink("ContriCbVl1");
    }

    /**
     * Container's getter for DeclarationVO1.
     * @return DeclarationVO1
     */
    public ViewObjectImpl getDeclarationVO1() {
        return (ViewObjectImpl) findViewObject("DeclarationVO1");
    }

    /**
     * Container's getter for ContriDecVL1.
     * @return ContriDecVL1
     */
    public ViewLinkImpl getContriDecVL1() {
        return (ViewLinkImpl) findViewLink("ContriDecVL1");
    }

    /**
     * Container's getter for ReclamationVO1.
     * @return ReclamationVO1
     */
    public ViewObjectImpl getReclamationVO1() {
        return (ViewObjectImpl) findViewObject("ReclamationVO1");
    }

    /**
     * Container's getter for ContriRecVL1.
     * @return ContriRecVL1
     */
    public ViewLinkImpl getContriRecVL1() {
        return (ViewLinkImpl) findViewLink("ContriRecVL1");
    }

    /**
     * Container's getter for ImpotcontribuableVO1.
     * @return ImpotcontribuableVO1
     */
    public ViewObjectImpl getImpotcontribuableVO1() {
        return (ViewObjectImpl) findViewObject("ImpotcontribuableVO1");
    }

    /**
     * Container's getter for ContriImpotVL1.
     * @return ContriImpotVL1
     */
    public ViewLinkImpl getContriImpotVL1() {
        return (ViewLinkImpl) findViewLink("ContriImpotVL1");
    }
}

